### PR TITLE
Fix Issue#19 and make aesthic updates and integrate a custom built printer to make ui more beautiful

### PR DESCRIPTION
**Pull request by IamMU**
# Fixes
 - #19 
 - Make adding #2 HTTP Requests easier
 - Make adding customization easier #18

### CODE REVIEW

**Review by mrpandya — CHANGES_REQUESTED** [review]
the beautifications are good.

can you also add the screenshots added in #19 to the README.md for the users to get an idea of how the UI will look?

**Comment by IamMU** [comment]
Sure, should I also add screenshots with steps?

**Comment by IamMU** [comment]
Hmm somehow the images are not being displayed, I'll do another commit with the right way

**Review by mrpandya — APPROVED** [review]

**Comment by mrpandya** [comment]
good work @IamMU 👍🏻

**Pull request merged**
